# PR Checks Trigger
apiVersion: cloudbuild.googleapis.com/v1
kind: BuildTrigger
metadata:
  name: pr-${PROJECT_NAME}
description: Trigger for PR checks
location: ${REGION}
projectId: ${CICD_RUNNER_PROJECT_ID}
serviceAccount: ${CICD_RUNNER_SA_EMAIL}
repositoryEventConfig:
  repository: projects//locations/us-central1/connections/${HOST_CONNECTION_NAME}/repositories/${REPOSITORY_NAME}
  pullRequest:
    branch: main
filename: deployment/ci/pr_checks.yaml
includedFiles:
  - app/**
  - data_ingestion/**
  - tests/**
  - deployment/**
  - uv.lock
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
---
# CD Pipeline Trigger
apiVersion: cloudbuild.googleapis.com/v1
kind: BuildTrigger
metadata:
  name: cd-${PROJECT_NAME}
description: Trigger for CD pipeline
location: ${REGION}
projectId: ${CICD_RUNNER_PROJECT_ID}
serviceAccount: ${CICD_RUNNER_SA_EMAIL}
repositoryEventConfig:
  repository: projects/${CICD_RUNNER_PROJECT_ID}/locations/${REGION}/connections/${HOST_CONNECTION_NAME}/repositories/${REPOSITORY_NAME}
  push:
    branch: main
filename: deployment/cd/staging.yaml
includedFiles:
  - app/**
  - data_ingestion/**
  - tests/**
  - deployment/**
  - uv.lock
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
substitutions:
  _STAGING_PROJECT_ID: ${STAGING_PROJECT_ID}
  _BUCKET_NAME_LOAD_TEST_RESULTS: ${LOAD_TEST_BUCKET_NAME}
  _REGION: ${REGION}
  _CONTAINER_NAME: ${PROJECT_NAME}
  _ARTIFACT_REGISTRY_REPO_NAME: ${ARTIFACT_REPO_ID}
  _CLOUD_RUN_APP_SA_EMAIL: ${CLOUD_RUN_APP_SA_STAGING}
---
# Deploy to Production Trigger
apiVersion: cloudbuild.googleapis.com/v1
kind: BuildTrigger
metadata:
  name: deploy-${PROJECT_NAME}
description: Trigger for deployment to production
location: ${REGION}
projectId: ${CICD_RUNNER_PROJECT_ID}
serviceAccount: ${CICD_RUNNER_SA_EMAIL}
repositoryEventConfig:
  repository: projects/${CICD_RUNNER_PROJECT_ID}/locations/${REGION}/connections/${HOST_CONNECTION_NAME}/repositories/${REPOSITORY_NAME}
filename: deployment/cd/deploy-to-prod.yaml
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
approvalConfig:
  approvalRequired: true
substitutions:
  _PROD_PROJECT_ID: ${PROD_PROJECT_ID}
  _REGION: ${REGION}
  _CONTAINER_NAME: ${PROJECT_NAME}
  _ARTIFACT_REGISTRY_REPO_NAME: ${ARTIFACT_REPO_ID}
  _CLOUD_RUN_APP_SA_EMAIL: ${CLOUD_RUN_APP_SA_PROD}
